### ISSUE TITLE
Migrations:diff doesn't create any audit tables

### ISSUE THREAD

**Issue by Rezaldy** [somnambulist-tech/laravel-doctrine-entity-audit#2]
Hi!

I was hoping you could help me with what I'm doing wrong. I followed the steps in the readme;

- composer require somnambulist/laravel-doctrine-entity-audit
- Added serviceprovider for laravel-doctrine-entity-audit _after_ the one for Laravel Doctrine
- ran `php artisan vendor:publish`
- Added entities I wanted to track under `entity_audit.entity_managers.default.entities`
- `php artisan doctrine:migrations:diff`

But here's where it goes wrong; The migration that has been generated contains no audit tables at all. Is there anything that I'm missing?

**Comment by dave-redfern** [comment]
@Rezaldy Hi, I've just seen your issue. In theory, that should be all that is needed. I need to check if there are missing steps. I'll respond again shortly.

**Comment by dave-redfern** [comment]
@Rezaldy So here's what I did to test the integration:

 * I made a brand new Laravel project using `composer create-project laravel/laravel project`
 * `composer req laravel-doctrine/orm doctrine/inflector:"^1.4|^2.0"`
 * `composer req laravel-doctrine/migrations`
 * `composer req somnambulist/laravel-doctrine-entity-audit`
 * added entity-audit to config/app.php (no auto-discover on that package, I should probably set that up)
 * `./artisan vendor:publish`
 * copied the fixture test classes from this repo to the test project and set namespace to `App\Entities`
 * set the DB to sqlite and left DB_DATABASE blank for the default sqlite db name
 * `./artisan doctrine:schema:validate` (ok)
 * `./artisan doctrine:migrations:diff`
 * generated a diff file with the revisions table, but not audit tables because I left out what to audit...
 * added Animal and Article to the list of entities on the default entity manager in `config/entity_audit.php`
 * `./artisan doctrine:migrations:diff`
 * migration has audit tables prefixed with: revision_audit_

Did you add the service provider to your app.php config file? It is not automatically added.
If you did: do you have a custom named entity manager i.e. it is not under the "default" key in the doctrine.php config file? If this, you need to add that key to the entity_audit.php config file (default is there as an example).
Did you forget to add the entities you want to audit to the entity_audit config?

If you are missing the first, auditing wont be running; the latter points, nothing will get audited unless you explicitly enable those entities to be audited.

**Comment by dave-redfern** [comment]
Yes, check your logs for any errors. Though typically with doctrine if something goes wrong you know about since the artisan command wont work.

You would also want to check your environment. For example: if using Docker does your container have the latest files inside it, are your config files good and mappings correct etc etc.

**Comment by Rezaldy** [comment]
Docker has the latest files in it, so that shouldn't be it. I have so far found that the afterResolving call is registered at first by the package, but then the Illuminate Service Container says it has no callbacks on `afterResolvingCallBacks`..

**Comment by Rezaldy** [comment]
We have a provider that binds certain new app values. Having this provider in apparently meant that the calls were being bound on every request. It apparently also made it so that whatever LDEA was trying to do was cleared. Commenting out that provider actually made things work again.

Odd, but we found it. Thank you for your help.

**Comment by dave-redfern** [comment]
@Rezaldy glad to hear you figured out what was going on! If you find other issues, please make issues and feel free to tag me on them so I get notified.
